print("      ______")
print("|     |     ")
print("|     |     ")
print("|_____|_____")
print("      |    |")
print("      |    |")
print("______|    |")
print("			   ")
print("Heil Hitler!")
print("			   ")